{% set name = "impunity" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/impunity-{{ version }}.tar.gz
  sha256: 5aa9937e7574affdeb2b5272a33048d2361dce843ae6460400e0efce0974243a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - pint >=0.19.2
    - astor >=0.8.1
    - typing-extensions >=4.2.0,<5.0.0

test:
  imports:
    - impunity
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/achevrot/impunity
  summary: Static checking for consistency of physical units
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - xoolive
